[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../pigs/base", features = ["net"] }
paste = "1.0"

#[patch.crates-io]
#reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }