[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../pigs/common", features = ["net"] }
paste = "1.0"
poem-openapi = { version = "5.1", features = ["swagger-ui"] }

#[patch.crates-io]
#reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }