[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../../pigs/base", features = ["net"] }
paste = "1.0"

# 共享依赖
utoipa.workspace = true
anyhow.workspace = true
