[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
base = { git = "https://github.com/epimore/pigs.git",rev = "10bbe44", features = ["net"] }
paste = "1.0"

# 共享依赖
utoipa.workspace = true
anyhow.workspace = true
